"""
File Name: main_info_theory.py

Author: Rachel Newman

Purpose: This file creates simple data, both randomly generated and sample
data generated by the creator. Calculations for information theory are run
with the package 'Information_Theory' implementing equations on the
predefined discrete data. 

This file contains two sections: Information Theory Calculations for 
User-Created Data and Information Theory Calculations for Random Discrete Data.

Please note: The package used was created by the author of this script and
only contains functions for discrete data. Functions for continous data 
will be created and added later to this project.
"""
import numpy as np
from Information_Theory import (
    probabilities,
    entropy, 
    joint_entropy,
    joint_entropy_3,
    mutual_information, 
    conditional_mutual_information
)

"Information Theory Calculations for User-Created Data"
# --------------------------------------------------------------------------

# User-created data
x_data = [5, 3, 6, 7, 19, 0, 2, 1, 0, 7, 0, 2, 5] # simple data
y_data = [2, 14, 9, 1, 0, 23, 1, 0, 11, 1, 9, 1] # creating data for joint entropy
z_data = [1, 0, 3, 7, 0, 11, 5, 1, 8, 2, 6, 19] # creating data for conditional mutual information

# --------------------------------------------------------------------------

# Displaying probability distributions (histograms) at each state
print("Probability Distributions for User-Created Data:")
print("Probability distribution X:\n", probabilities(x_data))
print("\nProbability distribution Y:\n", probabilities(y_data))
print("\nProbability distribution Z:\n", probabilities(z_data))

# --------------------------------------------------------------------------

# Entropy calculations for each variable
H_X = entropy(x_data)
H_Y = entropy(y_data)
H_Z = entropy(z_data) # entropy for z data

print("Entropy of User-Created Variables:")
print("H(X):", H_X)
print("\nH(Y):", H_Y)
print("\nH(Z):", H_Z)

# --------------------------------------------------------------------------

# Joint entropy calculations for 2 variables
H_XY = joint_entropy(x_data, y_data)
H_XZ = joint_entropy(x_data, z_data)
H_YZ = joint_entropy(y_data, z_data)

print("\nJoint Entropy of 2 variables:")
print("H(X,Y):", H_XY)
print("\nH(X,Z):", H_XZ)
print("\nH(Y,Z):", H_YZ)

# --------------------------------------------------------------------------

# Joint entropy calculations for all 3 variables
H_XYZ = joint_entropy_3(x_data, y_data, z_data) 
print("\nJoint entropy H(X,Y,Z):", H_XYZ)

# --------------------------------------------------------------------------

# Mutual information I(X;Y)
I_XY = mutual_information(x_data, y_data)
I_XZ = mutual_information(x_data, z_data)
I_YZ = mutual_information(y_data, z_data)

print("\nMutual Information:")
print("I(X;Y):", I_XY)
print("\nI(X;Z):", I_XZ)
print("\nI(Y;Z):", I_YZ)

# --------------------------------------------------------------------------

# Conditional Mutual Information I(X;Y|Z)
conditional_MI = conditional_mutual_information(x_data, y_data, z_data)
print("\nConditional Mutual Information I(X;Y|Z):", conditional_MI)

# --------------------------------------------------------------------------



"Information Theory Calculations for Random Discrete Data"
# --------------------------------------------------------------------------

# random discrete data
np.random.seed(0) # setting seed for reproducibility

# creating random integers between 0 and 9, with an array lenght of 20
X = np.random.randint(0, 10, 20).tolist()
Y = np.random.randint(0, 10, 20).tolist()
Z = np.random.randint(0, 10, 20).tolist()

# printing the data just to see what was created
print("\nRandom X data:", X)
print("\nRandom Y data:", Y)
print("\nRandom Z data:", Z)

# --------------------------------------------------------------------------

# Displaying probability distributions at each random state
print("\nProbability Distributions for Random Discrete Variables:")
print("X:\n", probabilities(X))
print("\nY:\n", probabilities(Y))
print("\nZ:\n", probabilities(Z))

"""
Note: Although X and Z take different random values, they have the same 
shape for their probability distributions, meaning entropy is the exact same.
This illustrates the notion that entropy depends on the probability 
distribution of each variable, not on the specific variable labels.
"""

# --------------------------------------------------------------------------

# Entropy for Random Data
H_rand_X = entropy(X)
H_rand_Y = entropy(Y)
H_rand_Z = entropy(Z)

print("\nEntropy for each random variable:")
print("H(X):", H_rand_X)
print("\nH(Y):", H_rand_Y)
print("\nH(Z):", H_rand_Z)

# --------------------------------------------------------------------------

# Joint Entropy for 2 random variables
H_rand_XY = joint_entropy(X, Y)
H_rand_XZ = joint_entropy(X, Z)
H_rand_YZ = joint_entropy(Y, Z)

print("\nJoint Entropy of 2 random variables:")
print("H(X,Y):", H_rand_XY)
print("\nH(X,Z):", H_rand_XZ)
print("\nH(Y,Z):", H_rand_YZ)

# --------------------------------------------------------------------------

# Joint Entropy for all 3 random variables

H_rand_XYZ = joint_entropy_3(X, Y, Z)

print("\nJoint entropy of 3 variables:")
print("H(X,Y,Z):", H_rand_XYZ)

# --------------------------------------------------------------------------

# Mutual Information I(X;Y)

MI_rand_XY = mutual_information(X, Y)
MI_rand_XZ = mutual_information(X, Z)
MI_rand_YZ = mutual_information(Y, Z)

print("\nMutual Information for random variables:")
print("I(X;Y):", MI_rand_XY)
print("\nI(X;Z):", MI_rand_XZ)
print("\nI(Y;Z):", MI_rand_YZ)

# --------------------------------------------------------------------------

# Conditional Mutual Information I(X;Y|Z)
CMI_rand_XY_Z = conditional_mutual_information(X, Y, Z)
print("\nConditional Mutual Information:")
print("I(X;Y|Z):", CMI_rand_XY_Z)